spring:
  application:
    name:spring-ai

spring:
  ai:
    openai:
      api-key:${OPENAI_API_KEY}

spring
  logging:
    level:
      org:
        springframework:
          web:DEBUG

com:
  poc:
    ai:
      vectorStorePath: /tmp/vectorStore.json