spring:
  application:
    name: spring-ai

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

com:
  poc:
    ai:
      properties:
        vectorStorePath: /resources/vectorStore.json
        documentsToLoad:
          - classpath:/movies500.csv